### PR TITLE
Small changes to deal with exception and dynamic language highlighting

### PR DESCRIPTION
**Pull request by saleslessa**

### CODE REVIEW

**Comment by lijunle** [comment]
Hi, @saleslessa 

I am not actively working on this project for a long time (actually I am not writing C# for a long time). With your touches, I suppose you have more knowledge on this project than me. 😄 

Do you mind to be the collaborator of this project? Thanks!

**Comment by saleslessa** [comment]
Hi @lijunle, 
It will be awesome. If you have no problems with that, I can continue the development.

Thanks

**Comment by saleslessa** [comment]
Hi @lijunle,
After commit my changes a error occurred when appveyor try to publish on Nuget Server.. The error is that the API_KEY of symbol_server is somehow outdated.
I tried to omit this call to symbol server to make build pass for now...
Could you take a look to update this API key?

Thanks.

**Comment by lijunle** [comment]
Where to find the error message?

**Comment by saleslessa** [comment]
I changed back the configuration to publish automatically on Nuget Server.. in a few minutes the appveyour status will change to failing. There (appveyour) you can see the error message

**Comment by lijunle** [comment]
Are you talking about this one? https://ci.appveyor.com/project/lijunle/vsxmd/build/0.0.0.134

It shows SSL/TLS secure error

**Comment by saleslessa** [comment]
Yes.

**Comment by lijunle** [comment]
Seems a common issue: https://twitter.com/mattbrailsford/status/1019891621712842753?s=09

**Comment by saleslessa** [comment]
Hi @lijunle, After do some research about, I think that your Nuget API key is expired. Could you put me as package contributor in Nuget.org? so I can create an API key with my account and maintain the package there also.
Thanks.

**Comment by lijunle** [comment]
@saleslessa Sorry for my late, what is your Nuget.org account username?

image

**Comment by saleslessa** [comment]
Hi,

Username: saleslessalopes
E-mail account: lopesdealencar@gmail.com

**Pull request merged**
