### PR TITLE
Add MSBuild namespace to Vsxmd.targets

### PR DESCRIPTION
**Pull request by benjspriggs**
## summary

This PR addresses issues raised by #68.

### CODE REVIEW

**Comment by benjspriggs** [comment]
Pinging @lijunle for review.

**Comment by lijunle** [comment]
@benjspriggs If we want to ensure VS2015 support, it is worth to declare `VS2015` in [AppVeyor CI](https://github.com/lijunle/Vsxmd/blob/master/appveyor.yml#L4).

**Comment by lijunle** [comment]
@benjspriggs I [tried](https://ci.appveyor.com/project/lijunle/vsxmd/builds/24155731/job/oqe41k90qbn7exf9) to declare VS2015 as official support but found the CSPROJ file format is completely changed from MSBuild14 to dotnet. I feel like it is not worth to *officially* support VS2015. But if you think this one line change could solve your problem, I could like to merge it. OK?

**Comment by benjspriggs** [comment]
It seems the Appveyor error is coming from an [incompatibility between the VS2017+ versions of `.csproj` files and the VS2015 versions of `.csproj` files](https://devblogs.microsoft.com/dotnet/announcing-net-core-tools-msbuild-alpha/#div-comment-164606).

Ultimately, I don't think it'd be worth it to convert the `Vsxmd.csproj` file to a VS2015 compatible format, but I do think it'd be worth it for VS2015 to at least be able to use this via Nuget. If it's possible this fixes the problem, I would like to merge it, even if building via VS2015 isn't officially supported.

**Pull request merged**
